export type Payment = {
    id: string,
    accessCode?: string,
    transactionReference: string,
    amount: number,
    callBackUrl?: string,
    currency: string,
    description?: string,
    merchantRequestId?: string,
    checkoutRequestId?: string,
    email?: string,
    paymentMode: string,
    phoneNumber?: string,
    resourceId: string,
    resourceName: string,
    resourceType: string,
    transactionId: string,
    status: string,
    userId: string,
    paymentPeriod: number,
    periodType: string,
    isRecurring: boolean,
    transactionDate: string,
    paystackResponse?: string,
    mpesaStkPushResponse?: string,
    createdAt: string,
    updatedAt: string,
}
